<%@ Page Title="" Language="vb" AutoEventWireup="false" MasterPageFile="~/Site.Master" CodeBehind="GenRouting.aspx.vb" Inherits="CUBE.GenRouting" %>
<%@ Register assembly="Telerik.Web.UI" namespace="Telerik.Web.UI" tagprefix="telerik" %>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
    <div id="clear">&nbsp;</div>
<div id="header" class="header">
   <h1>Routing CODEs</h1>
</div>
<div id="clear">
    </div>
<div>
    <telerik:RadGrid ID="rgServers" runat="server" 
        GridLines="None" AllowPaging="True" 
        AutoGenerateColumns="False" DataMember="DefaultView" 
        AllowAutomaticUpdates="True" AllowAutomaticDeletes="True" 
        AllowAutomaticInserts="True" AllowFilteringByColumn="True" CellSpacing="0" 
        AutoGenerateDeleteColumn="True">
        <MasterTableView CommandItemDisplay="Top" DataMember="DefaultView" 
            EditMode="EditForms" datakeynames="ID">
<CommandItemSettings ExportToPdfText="Export to PDF"></CommandItemSettings>

            <RowIndicatorColumn>
                <HeaderStyle Width="20px"></HeaderStyle>
            </RowIndicatorColumn>
            <ExpandCollapseColumn>
                <HeaderStyle Width="20px"></HeaderStyle>
            </ExpandCollapseColumn>
            <EditFormSettings>
                <EditColumn UniqueName="EditCommandColumn1">
                </EditColumn>
            </EditFormSettings>
            <Columns>
                <telerik:GridBoundColumn DataField="ID" DataType="System.Int32" HeaderText="ID" 
                    ReadOnly="True" SortExpression="ID" UniqueName="ID" Display="False" >
                </telerik:GridBoundColumn>
                <telerik:GridBoundColumn DataField="RouteUsername" HeaderText="Username" 
                    SortExpression="RouteUsername" UniqueName="RouteUsername" 
                    FilterControlAltText="Filter RouteUsername column">
                </telerik:GridBoundColumn>
                <telerik:GridBoundColumn DataField="Reference" HeaderText="Reference" 
                    SortExpression="Reference" UniqueName="Reference" AllowFiltering="False" 
                    FilterControlAltText="Filter Reference column">
                </telerik:GridBoundColumn>
            </Columns>
        </MasterTableView>
        <ClientSettings>
            <Selecting AllowRowSelect="True" />
        </ClientSettings>

<FilterMenu EnableTheming="True">
<CollapseAnimation Type="OutQuint" Duration="200"></CollapseAnimation>
</FilterMenu>

<HeaderContextMenu CssClass="GridContextMenu GridContextMenu_Default"></HeaderContextMenu>
    </telerik:RadGrid>
    <br />
    <telerik:RadButton ID="cmdGenerate" runat="server" Text="Generate Routing File"></telerik:RadButton>
</div>
</asp:Content>
